//! CLI + configuration.
//!
//! `sophia-mcp` with no args aims at a LOCAL headless garden (the out-of-the-box
//! hero). `sophia-mcp --backend <url>` points at an existing backend (a platform-next
//! gateway cell `/o/{owner}/g/{id}/mcp`, or any garden loopback `/mcp`).

use std::path::PathBuf;

use clap::Parser;

/// Stdio MCP server that proxies to a Mnemosyne/garden backend.
///
/// Tools are autopopulated from the backend (tools/list + tools/call
/// passthrough) — sophia-mcp never hardcodes them. Garden owns the tools; sophia-mcp owns
/// who-you-are, which-graph, and which-backend.
#[derive(Debug, Clone, Parser)]
#[command(name = "sophia-mcp", version, about, long_about = None)]
pub struct Cli {
    /// Backend selector. Either the literal `local` (start + proxy to a headless
    /// garden on this machine) or a URL to an existing backend's MCP endpoint
    /// (e.g. `https://gw.example` with `--owner` + `--graph`, or
    /// `http://127.0.0.1:8086/mcp`). Defaults to `local`.
    #[arg(long, default_value = "local", env = "SOPHIA_MCP_BACKEND")]
    pub backend: String,

    /// Bearer token for a REMOTE backend. For a platform-next gateway this is a
    /// Cognito JWT, a dev token, or the shared service token (`PN_SERVICE_TOKEN`
    /// / `MNEMOSYNE_SERVICE_TOKEN`). Ignored for `--backend local` (the local
    /// loopback token is generated by sophia-mcp).
    #[arg(long, env = "SOPHIA_MCP_TOKEN")]
    pub token: Option<String>,

    /// Service-auth "on behalf of" subject. When set against a gateway, sophia-mcp
    /// sends `x-pn-on-behalf-of: <sub>` and the gateway runs its own per-graph
    /// ACL for that end-user. Use with a service token in `--token`.
    #[arg(long, env = "SOPHIA_MCP_ON_BEHALF_OF")]
    pub on_behalf_of: Option<String>,

    /// Fallback user id side-channel (`X-User-ID`) for hosted/sidecar auth modes
    /// where the bearer is opaque. Only sent when `--on-behalf-of` is NOT set.
    #[arg(long, env = "SOPHIA_MCP_USER_ID")]
    pub user_id: Option<String>,

    /// Local graph id. A remote cloud-2 gateway requires this together with
    /// `--owner`; sophia-mcp proves discovery via `/control/mcp`, activates the
    /// tuple, and binds `<base>/o/<owner>/g/<graph>/mcp`. For
    /// LOCAL it selects the default graph the agent operates on (advisory;
    /// graph selection inside one local profile is via the graph tools).
    #[arg(long, env = "SOPHIA_MCP_GRAPH")]
    pub graph: Option<String>,

    /// Stable typed graph owner (`user:<subject>`) for a remote cloud-2
    /// gateway. Remote base URLs require both owner and graph so a local graph
    /// name is never treated as globally unique.
    #[arg(long, env = "SOPHIA_MCP_OWNER")]
    pub owner: Option<String>,

    // ---- LOCAL backend knobs (ignored for remote) ----
    /// Profile/data directory for the local headless garden. Created on first
    /// run. Defaults to `~/.sophia-mcp/profile`.
    #[arg(long, env = "SOPHIA_MCP_PROFILE_DIR")]
    pub profile_dir: Option<PathBuf>,

    /// Path to the `gardend` binary for the LOCAL backend. If unset, sophia-mcp looks
    /// for `gardend` on PATH and at `../garden/src-tauri/target/release/gardend`
    /// relative to the sophia-mcp binary.
    #[arg(long, env = "SOPHIA_MCP_GARDEN_BIN")]
    pub garden_bin: Option<PathBuf>,

    /// Loopback port for the LOCAL garden. `0` = OS-assigned (sophia-mcp then reads
    /// the chosen port from the loopback manifest).
    #[arg(long, default_value_t = 0, env = "SOPHIA_MCP_LOCAL_PORT")]
    pub local_port: u16,

    /// Seconds to wait for the LOCAL garden `/health` before giving up.
    #[arg(long, default_value_t = 30, env = "SOPHIA_MCP_LOCAL_HEALTH_TIMEOUT")]
    pub local_health_timeout: u64,
}

impl Cli {
    /// Is the LOCAL backend selected?
    pub fn is_local(&self) -> bool {
        self.backend.eq_ignore_ascii_case("local")
    }

    /// Default local profile dir: `~/.sophia-mcp/profile`.
    pub fn resolved_profile_dir(&self) -> PathBuf {
        if let Some(dir) = &self.profile_dir {
            return dir.clone();
        }
        let home = std::env::var_os("HOME")
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from("."));
        home.join(".sophia-mcp").join("profile")
    }
}
