//! CLI + configuration.
//!
//! `sophia-mcp` with no args aims at a LOCAL headless garden (the out-of-the-box
//! hero). `sophia-mcp --backend <url>` points at an existing backend (a platform-next
//! gateway cell `/o/{owner}/g/{id}/mcp`, or any garden loopback `/mcp`).

use std::path::PathBuf;

use clap::Parser;

/// Stdio MCP server that proxies to a Mnemosyne/garden backend.
///
/// Tools are autopopulated from the backend (tools/list + tools/call
/// passthrough) — sophia-mcp never hardcodes them. Garden owns the tools; sophia-mcp owns
/// who-you-are, which-graph, and which-backend.
#[derive(Debug, Clone, Parser)]
#[command(name = "sophia-mcp", version, about, long_about = None)]
pub struct Cli {
    /// Backend selector. Either the literal `local` (start + proxy to a headless
    /// garden on this machine) or a URL to an existing backend's MCP endpoint
    /// (e.g. `https://gw.example` with `--owner` + `--graph`, or
    /// `http://127.0.0.1:8086/mcp`). Defaults to `local`.
    #[arg(long, default_value = "local", env = "SOPHIA_MCP_BACKEND")]
    pub backend: String,

    /// Bearer token for a REMOTE backend. For a platform-next gateway this is a
    /// Cognito JWT, a dev token, or the shared service token (`PN_SERVICE_TOKEN`
    /// / `MNEMOSYNE_SERVICE_TOKEN`). Ignored for `--backend local` (the local
    /// loopback token is generated by sophia-mcp).
    ///
    /// Prefer `SOPHIA_MCP_TOKEN` over this flag: a token passed on the command
    /// line is visible to anyone who can list this machine's processes (`ps`,
    /// `/proc`, a process-list API) for as long as sophia-mcp runs, and often
    /// ends up in shell history too. The flag keeps working — for one-off
    /// local testing, or an environment that already isolates argv — but the
    /// env var is the one to reach for by default.
    #[arg(long, env = "SOPHIA_MCP_TOKEN")]
    pub token: Option<String>,

    /// Service-auth "on behalf of" subject. When set against a gateway, sophia-mcp
    /// sends `x-pn-on-behalf-of: <sub>` and the gateway runs its own per-graph
    /// ACL for that end-user. Use with a service token in `--token`.
    #[arg(long, env = "SOPHIA_MCP_ON_BEHALF_OF")]
    pub on_behalf_of: Option<String>,

    /// Fallback user id side-channel (`X-User-ID`) for hosted/sidecar auth modes
    /// where the bearer is opaque. Only sent when `--on-behalf-of` is NOT set.
    #[arg(long, env = "SOPHIA_MCP_USER_ID")]
    pub user_id: Option<String>,

    /// Local graph id. A remote cloud-2 gateway requires this together with
    /// `--owner`; sophia-mcp proves discovery via `/control/mcp`, activates the
    /// tuple, and binds `<base>/o/<owner>/g/<graph>/mcp`. For
    /// LOCAL it selects the default graph the agent operates on (advisory;
    /// graph selection inside one local profile is via the graph tools).
    #[arg(long, env = "SOPHIA_MCP_GRAPH")]
    pub graph: Option<String>,

    /// Stable typed graph owner (`user:<subject>`) for a remote cloud-2
    /// gateway. Remote base URLs require both owner and graph so a local graph
    /// name is never treated as globally unique.
    #[arg(long, env = "SOPHIA_MCP_OWNER")]
    pub owner: Option<String>,

    /// Allow sending a bearer token (`--token`/`SOPHIA_MCP_TOKEN`, a sub's
    /// `--sub-token`, or the gateway service token) over plain `http://` to a
    /// non-loopback host. Default `false`: sophia-mcp refuses to build a
    /// client that would ship a real credential in the clear to anything
    /// that isn't 127.0.0.0/8, `::1`, or `localhost` — those stay allowed
    /// unconditionally (the LOCAL backend's whole mechanism). Use `https://`
    /// instead where you can; reach for this only for a deliberately
    /// plaintext internal deployment.
    #[arg(long, default_value_t = false, env = "SOPHIA_MCP_ALLOW_INSECURE_HTTP")]
    pub allow_insecure_http: bool,

    // ---- REMOTE gateway knobs ----
    /// Seconds to wait for a graph cell to become ROUTABLE (activation
    /// `phase: ready` AND a successful MCP `initialize` on the cell path)
    /// before a request is answered with a truthful JSON-RPC error carrying the
    /// last observed activation state. Waking a dormant cell takes minutes.
    /// Gateway-only (LOCAL and direct `/mcp` have no activation concept).
    #[arg(long, default_value_t = 300, env = "SOPHIA_MCP_ACTIVATION_TIMEOUT")]
    pub activation_timeout: u64,

    /// Seconds between activation polls (`GET /activations/{id}`) and between
    /// retries of a cell path that answered 202/502/503. Gateway-only.
    #[arg(long, default_value_t = 2, env = "SOPHIA_MCP_ACTIVATION_POLL")]
    pub activation_poll: u64,

    /// Per-request ceiling (seconds) for any single HTTP request — the whole
    /// request: connect, send, and read the full response. Applies to every
    /// backend (LOCAL's proxy to gardend's loopback, a direct `--backend
    /// <url>/mcp`, every sub-MCP, and the gateway). Against a gateway,
    /// activation-wait requests are additionally bounded by the remaining
    /// `--activation-timeout`, so a hung upstream can never stretch a wait
    /// past its budget.
    #[arg(long, default_value_t = 120, env = "SOPHIA_MCP_REQUEST_TIMEOUT")]
    pub request_timeout: u64,

    /// If the gateway answers HTTP 404 for `POST {base}/control/mcp`, also try
    /// the unified `{base}/mcp` for the control-plane tools. Off by default:
    /// today's gateway serves control tools only at `/control/mcp`.
    /// Gateway-only.
    #[arg(long, default_value_t = false, env = "SOPHIA_MCP_UNIFIED_MCP_FALLBACK")]
    pub unified_mcp_fallback: bool,

    // ---- LOCAL backend knobs (ignored for remote) ----
    /// Profile/data directory for the local headless garden. Created on first
    /// run. Defaults to `~/.sophia-mcp/profile`.
    #[arg(long, env = "SOPHIA_MCP_PROFILE_DIR")]
    pub profile_dir: Option<PathBuf>,

    /// Path to the `gardend` binary for the LOCAL backend. If unset, sophia-mcp looks
    /// for a `gardend` next to its own binary, then at the sibling garden checkout's
    /// headless example target — `../garden/src-tauri/target/release/examples/gardend`
    /// relative to the current directory (falling back to the `debug` variant) —
    /// then finally on `PATH` (see `backend::local::resolve_gardend_bin_from`).
    #[arg(long, env = "SOPHIA_MCP_GARDEN_BIN")]
    pub garden_bin: Option<PathBuf>,

    /// Loopback port for the LOCAL garden. `0` = OS-assigned (sophia-mcp then reads
    /// the chosen port from the loopback manifest).
    #[arg(long, default_value_t = 0, env = "SOPHIA_MCP_LOCAL_PORT")]
    pub local_port: u16,

    /// Seconds to wait for the LOCAL garden `/health` before giving up.
    #[arg(long, default_value_t = 30, env = "SOPHIA_MCP_LOCAL_HEALTH_TIMEOUT")]
    pub local_health_timeout: u64,

    // ---- Sub-MCPs (composed above ANY backend: local, remote, or gateway) ----
    /// Mount a namespaced sub-MCP: `<prefix>=<url>`, e.g. `layout=http://127.0.0.1:5199/mcp`.
    /// Repeatable. Its bare tool names (`world`, `moves`, …) are exposed to the
    /// agent as `<prefix>_<name>` (`layout_world`); a `tools/call` whose name
    /// starts with `<prefix>_` routes there, bare name, arguments untouched. A
    /// sub that fails its one `tools/list` probe at start is skipped (logged to
    /// stderr, never the token) — the rest of the catalog still serves. `prefix`
    /// must match `[a-z][a-z0-9]*`. Env `SOPHIA_MCP_SUBS` is a comma-separated
    /// list of the same `prefix=url` pairs.
    #[arg(long = "sub", env = "SOPHIA_MCP_SUBS", value_delimiter = ',')]
    pub subs: Vec<String>,

    /// Bearer token for one sub-MCP: `<prefix>=<token>`. Repeatable. Sent only
    /// on requests to that sub — never to the primary backend or any other sub.
    /// A prefix with no matching `--sub` is harmless (unused). Env
    /// `SOPHIA_MCP_SUB_TOKENS` is a comma-separated list of the same
    /// `prefix=token` pairs.
    #[arg(
        long = "sub-token",
        env = "SOPHIA_MCP_SUB_TOKENS",
        value_delimiter = ','
    )]
    pub sub_tokens: Vec<String>,
}

impl Cli {
    /// Is the LOCAL backend selected?
    pub fn is_local(&self) -> bool {
        self.backend.eq_ignore_ascii_case("local")
    }

    /// Default local profile dir: `~/.sophia-mcp/profile`.
    pub fn resolved_profile_dir(&self) -> PathBuf {
        if let Some(dir) = &self.profile_dir {
            return dir.clone();
        }
        let home = std::env::var_os("HOME")
            .map(PathBuf::from)
            .unwrap_or_else(|| PathBuf::from("."));
        home.join(".sophia-mcp").join("profile")
    }

    /// Parse + validate `--sub` / `--sub-token` into [`SubSpec`]s. Empty when
    /// no `--sub` was given — the common case, where `ComposedBackend` is
    /// never built at all.
    pub fn resolved_subs(&self) -> anyhow::Result<Vec<SubSpec>> {
        parse_sub_specs(&self.subs, &self.sub_tokens)
    }
}

/// One configured sub-MCP, resolved from `--sub <prefix>=<url>` plus its
/// optional `--sub-token <prefix>=<token>`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SubSpec {
    pub prefix: String,
    pub url: String,
    pub token: Option<String>,
}

/// A bare, single-segment lowercase identifier: `[a-z][a-z0-9]*`. Refuses an
/// empty string, an uppercase letter anywhere (`Layout`), a leading digit
/// (`1x`), and any separator (`-`, `_`, `.`, whitespace).
fn valid_prefix(p: &str) -> bool {
    let mut chars = p.chars();
    match chars.next() {
        Some(c) if c.is_ascii_lowercase() => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_lowercase() || c.is_ascii_digit())
}

/// Parse the raw `--sub` / `--sub-token` strings (already split on `,` by
/// clap's `value_delimiter`, one `prefix=value` pair per element) into
/// validated [`SubSpec`]s. Refuses: a malformed pair (no `=`), an invalid or
/// duplicate prefix, and an empty url. A `--sub-token` prefix with no
/// matching `--sub` is silently unused, not an error.
pub fn parse_sub_specs(subs: &[String], sub_tokens: &[String]) -> anyhow::Result<Vec<SubSpec>> {
    let mut tokens: std::collections::HashMap<&str, &str> = std::collections::HashMap::new();
    for raw in sub_tokens {
        let (prefix, token) = raw
            .split_once('=')
            .ok_or_else(|| anyhow::anyhow!("--sub-token '{raw}' must be prefix=token"))?;
        if !valid_prefix(prefix) {
            anyhow::bail!("--sub-token prefix '{prefix}' is invalid: must match [a-z][a-z0-9]*");
        }
        if tokens.insert(prefix, token).is_some() {
            anyhow::bail!("--sub-token prefix '{prefix}' given more than once");
        }
    }

    let mut seen = std::collections::HashSet::new();
    let mut specs = Vec::with_capacity(subs.len());
    for raw in subs {
        let (prefix, url) = raw
            .split_once('=')
            .ok_or_else(|| anyhow::anyhow!("--sub '{raw}' must be prefix=url"))?;
        if !valid_prefix(prefix) {
            anyhow::bail!(
                "--sub prefix '{prefix}' is invalid: must match [a-z][a-z0-9]* (got '{prefix}')"
            );
        }
        if url.trim().is_empty() {
            anyhow::bail!("--sub '{raw}' has an empty url");
        }
        if !seen.insert(prefix) {
            anyhow::bail!("--sub prefix '{prefix}' given more than once");
        }
        specs.push(SubSpec {
            prefix: prefix.to_string(),
            url: url.to_string(),
            token: tokens.get(prefix).map(|t| t.to_string()),
        });
    }
    Ok(specs)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_valid_subs_and_pairs_matching_tokens() {
        let specs = parse_sub_specs(
            &[
                "layout=http://127.0.0.1:5199/mcp".into(),
                "obs2=http://x/mcp".into(),
            ],
            &["layout=secret-token".into()],
        )
        .unwrap();
        assert_eq!(
            specs,
            vec![
                SubSpec {
                    prefix: "layout".into(),
                    url: "http://127.0.0.1:5199/mcp".into(),
                    token: Some("secret-token".into()),
                },
                SubSpec {
                    prefix: "obs2".into(),
                    url: "http://x/mcp".into(),
                    token: None,
                },
            ]
        );
    }

    #[test]
    fn rejects_uppercase_and_leading_digit_prefixes() {
        for bad in ["Layout=http://x", "1x=http://x", "-x=http://x", "=http://x"] {
            let err = parse_sub_specs(&[bad.to_string()], &[]).unwrap_err();
            assert!(format!("{err}").contains("invalid"), "{bad}: {err}");
        }
    }

    #[test]
    fn rejects_malformed_pair_empty_url_and_duplicate_prefix() {
        assert!(parse_sub_specs(&["no-equals-sign".into()], &[]).is_err());
        assert!(parse_sub_specs(&["layout=".into()], &[]).is_err());
        assert!(
            parse_sub_specs(&["layout=http://a".into(), "layout=http://b".into()], &[]).is_err()
        );
    }

    #[test]
    fn an_unmatched_sub_token_prefix_is_not_an_error() {
        let specs = parse_sub_specs(&[], &["ghost=token".into()]).unwrap();
        assert!(specs.is_empty());
    }

    #[test]
    fn no_subs_is_the_empty_vec() {
        assert_eq!(parse_sub_specs(&[], &[]).unwrap(), vec![]);
    }
}
